도커 파일 추가
ssu-isteam/isteam pull request #88
Opened 2021-03-29 23:46 UTC by yeop-sang

1. 도커에서 오류나는 module 추가 (commit 52af36ff6fbe6a60a2b85d10322cec9437211934)
2. 도커 파일 추가 및 readme 파일에 사용법 추가 작성 (commit b33fc3c4ce1df0fdfce8cffdb76cbcce8e224425)

2021-03-30 03:07 UTC, 5d-jh requested changes

2021-03-30 03:07 UTC, 5d-jh commented on Dockerfile
> +CMD [".venv/bin/python", "manage.py", "runserver", "0.0.0.0:80"]
프로덕션 환경에선 runserver를 권장하지 않는걸로 알고 있습니다. [참고](https://stackoverflow.com/questions/23176592/deploying-django-by-python-manage-py-runserver-to-production-on-vps)

`scripts/on-isteam.sh` 참고해서 다음처럼 수정하는게 좋을것같아요.
```suggestion
CMD gunicorn isteam.wsgi:application --bind 0.0.0.0:8000
```

2021-03-30 03:07 UTC, 5d-jh commented on Dockerfile
> +WORKDIR /app
```suggestion
WORKDIR /app
COPY --from=0 /app/ .
```

2021-03-30 03:07 UTC, 5d-jh commented on Dockerfile
> +FROM python:3.8
CSS 파일 번들링을 해야합니다
```suggestion
FROM node:lts
WORKDIR /app
COPY . .
RUN npm i
RUN npm run bundle -- --mode production

FROM python:3.8
```

2021-03-30 03:07 UTC, 5d-jh commented on Dockerfile
> +RUN .venv/bin/python manage.py migrate
```suggestion
RUN ./manage.py migrate groupware --settings isteam.settings.production
RUN ./manage.py migrate --settings isteam.settings.production
# Static file 업로드
./manage.py collectstatic --noinput --settings isteam.settings.production
```

2021-03-30 04:42 UTC, yeop-sang commented on Dockerfile
> +FROM python:3.8
이건 잘 이해가 안되서 그러는데 설명 혹시 가능할까요?

2021-03-30 04:43 UTC, 5d-jh commented on Dockerfile
> +FROM python:3.8
여러개로 흩여저있는 CSS 파일들을 하나로 뭉쳐주는 작업을 하는거에요

2021-03-30 04:47 UTC, 5d-jh commented on Dockerfile
> +FROM python:3.8
https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

2021-03-30 04:49 UTC, yeop-sang commented on Dockerfile
> +WORKDIR /app
[해당 문서](https://docs.docker.com/engine/reference/builder/)에 따르면 --from은 결국에 이름 플레그인데 달아야하는 이유가 있을까요?

2021-03-30 04:53 UTC, 5d-jh commented on Dockerfile
> +WORKDIR /app
하나로 뭉친 CSS 파일을 다음 스테이지에서 사용해야하기때문에 달아둔거에요

2021-03-30 04:58 UTC, yeop-sang commented on Dockerfile
> +RUN .venv/bin/python manage.py migrate
poetry를 배제하고 사용하는 걸까요?

2021-03-30 04:59 UTC, yeop-sang commented on Dockerfile
> +FROM python:3.8
이걸 이용하면 아래 poetry에서 궂이 빌드할 필요가 없는 것이지요?

2021-03-30 05:00 UTC, 5d-jh commented on Dockerfile
> +RUN .venv/bin/python manage.py migrate
아뇨 그냥 설정파일을 좀 더 명확하게 지정해주고, static 파일들을 s3에 업로드하는 작업을 추가해준거에요(poetry랑 관계 없습니다)

`migrate groupware`를 먼저 빌드한 이유는 그렇게 안하면 어떨 때 오류가 발생할때가 있더라고요

2021-03-30 05:07 UTC, yeop-sang commented on Dockerfile
> +RUN .venv/bin/python manage.py migrate
현재 pip freeze가 아닌 poetry로 종속성을 관리하고 있어서 중간에 poetry를 설치해야하긴 합니다만 이럴꺼면 오히려 poetry를 빼고 npm과 pip 만으로 종속성을 관리해도 충분하지 않을까 생각됩니다. ~~그리고 poetry를 빌드 과정에서 생각보다 오래 걸려서 불편한건 제 이야기고요~~

2021-03-30 05:15 UTC, 5d-jh commented on Dockerfile
> +FROM python:3.8
아뇨 이 부분도 poetry랑 관련 없습니다

2021-03-30 05:20 UTC, 5d-jh commented on Dockerfile
> +RUN .venv/bin/python manage.py migrate
써보면 알겠지만 pip가 오히려 더 헬이라.. 이정도 단점은 충분히 감수할만 하다고 생각합니다.

2021-04-02 11:55 UTC, yeop-sang commented on Dockerfile
> +CMD [".venv/bin/python", "manage.py", "runserver", "0.0.0.0:80"]
scripts/on-isteam을 조금씩 조작하면서 gunicorn 사용법을 익힐려고 했는데 mac 환경에서는 실행 오류가 나네요.
혹시 gunicorn 사용법 대략적으로 알 수 있을까요?

2021-04-08 08:13 UTC, 5d-jh commented
빌드 & 배포 과정에서 어려움이 있기때문에 아쉽지만 이 PR은 닫도록 하겠습니다.

2021-04-08 08:13 UTC, closed without merging