Dev isteam intro
ssu-isteam/isteam pull request #91
Opened 2021-04-14 21:52 UTC by yeop-sang

#74 에 맞게 해당 항목을 수정하였다.
현재 방식에 맞게 static의 logos로 파일을 업로드하게 만들었으나 static/intro_images/ 로 변경하였으면 한다.

또한 admin에 해당 내용을 추가하여 내용을 업로드할 수 있으며, database에서 해당 내용을 지우지 않아도 반영할 수 있도록 activation column을 추가하였다.

2021-04-15 11:03 UTC, 5d-jh requested changes
구현이 복잡하진 않지만 테스트 추가 부탁드립니다
+ 마이그레이션도 확인 부탁

2021-04-16 03:10 UTC, 5d-jh approved these changes

2021-04-16 03:13 UTC, 5d-jh commented
LGTM

2021-04-22 07:06 UTC, yeop-sang commented
[_Look Good To Me_](https://www.dictionary.com/e/acronyms/lgtm/)
![](https://www.dictionary.com/e/wp-content/uploads/2018/05/lhtm-300x300.jpg)

2021-04-22 07:15 UTC, merged